### ISSUE TITLE
_API wrapper for Scratch!

### ISSUE THREAD

**Issue by idontlie** [savaka2/scratch-extensions-directory#14]
If you aren't submitting an extension delete this template.

Required stuff:

* JS file URL (preferably on GitHub Pages) (or if you want it hosted on this repo attach the file): File attached 
* Author(s) to be listed ([see directory if confused](http://savaka2.github.io/scratch-extensions-directory/)): thisisntme
* Description: This extension can add friends, love/favorite projects, read your messages and display scratch alerts! (batteries not included)

Optional stuff:

* Code on GitHub (url should contain "/blob/") (or Gist): 
* Docs URL: 
* Demo project URL (preferably on GitHub Pages): 

```
(function (ext) {
	ext._shutdown = function () {};

	ext._getStatus = function () {
		return {
			status: 2,
			msg: 'Installed and Ready'
		};
	};

	var descriptor = {
		blocks: [

			['', 'Display Scratch Alert %s', 'notify', 'Your message here!!!'],
			['', 'Follow %s', 'follow', 'thisisntme'],
			['', 'Love project with id %n', 'love', '57277422'],
			['', 'favorite project id %n', 'favorite', '105743123/'],
			['R', 'messages', 'messages', ''],
			['', 'shutdown with message %s', 'shutdown', 'This project has been shut down.'],
			['R', "%s 's followers (veryveryverybroken(notimplementedyet))", 'followers', 'thisisntme'],


		]
	};

	ext.notify = function (text) {
		ScratchExtensions.notify(text);
	};
	ext.love = function (projectID) {
		$.ajax({
			type: "PUT",
			url: "https://scratch.mit.edu/site-api/users/lovers/" + projectID + "/add/?usernames=" + Scratch.INIT_DATA.LOGGED_IN_USER.model.username,
			data: {
				usernames: Scratch.INIT_DATA.LOGGED_IN_USER.model.username
			}
		})
	}
	ext.favorite = function (projectID) {
		$.ajax({
			type: "PUT",
			url: "https://scratch.mit.edu/site-api/users/favoriters/" + projectID + "/add/?usernames=" + Scratch.INIT_DATA.LOGGED_IN_USER.model.username,
			data: {
				usernames: Scratch.INIT_DATA.LOGGED_IN_USER.model.username
			}
		})
	}
	ext.follow = function (user) {
		$.ajax({
			type: "PUT",
			url: "https://scratch.mit.edu/site-api/users/followers/" + user + "/add/",
			data: {
				usernames: Scratch.INIT_DATA.LOGGED_IN_USER.model.username
			}
		})

	}

	ext.messages = function (callback) {
		$.ajax({
			url: 'https://scratch.mit.edu/messages/ajax/get-message-count/',
			dataType: 'json',
			success: function (responseText) {
				messages = responseText['msg_count'];
				callback(messages);
			}
		})
	}

	ext.followers = function (inUser, callback) {

		var page = 1;
		$.get(location.protocol + "//scratch.mit.edu/users/" + inUser + "/followers/?page=1", loaded);
		$out = "test?"

		function loaded(data) {
			var $dom = $(data);
			var $users = $dom.find('span.title').children();
			for (var i = 0; i < $users.length; i++) {
				var user = $users[i].text.trim();
				$out = $out + user;
			}

			page++;
			$.get(location.protocol + "//scratch.mit.edu/users/" + inUser + "/followers/?page=" + page, loaded).fail(
				callback($users)

			);

		};

	}
	ext.shutdown = function (message) {
		document.write(message);
	}
	ScratchExtensions.register("API wrapper for Scratch", descriptor, ext);
})({});
```

**Comment by idontlie** [comment]
Here is the demo project :) https://scratch.mit.edu/projects/57277422/#editor

**Comment by savaka2** [comment]
Extensions are used on ScratchX, not Scratch. The blocks in your demo project that you shared on Scratch have become undefined. If you want a demo project for your extension please use ScratchX.

**Comment by idontlie** [comment]
They are undefined until you run my extension.... just copy and paste the sourcecode into the console once you have loaded the test project.

**Comment by idontlie** [comment]
They are undefined until you run my extension.... just copy and paste the sourcecode into the console once you have loaded the test project.

**Comment by savaka2** [comment]
That does not work. You have to use ScratchX to create projects with experimental extensions.

**Comment by idontlie** [comment]
Wait about  5 mins. I will show you.

**Comment by idontlie** [comment]
https://www.youtube.com/watch?v=V3NTNW3Obxc&feature=youtu.be

**Comment by savaka2** [comment]
Thanks, I don't know why it wasn't working before. You still need to use ScratchX to make easily loadable projects with experimental extensions. If you want your demo listed, please create it as an SBX file.

**Comment by idontlie** [comment]
Do I just download the scratch file and rename it to a .sbx ?

**Comment by savaka2** [comment]
I don't think a converter or method of conversion currently exists. (SBX files also store where the extensions should be loaded from.) If you want I will recreate it manually or you can.

Also I don't think the Scratch API stack blocks in your extension will work from ScratchX.

**Comment by idontlie** [comment]
The API will work as long as you are logged in to scratch on whatever browser you are running the extension in. If scratchX can't be run in browser then there's no point in a demo, otherwise the code in the demo should be very  easy to replicate.

**Comment by savaka2** [comment]
ScratchX is a website and can only be run in the browser. If you don't know about ScratchX, [please go read about it so you understand it](http://scratchx.org/#faq).
Then decide whether or not you want a demo project.
Also I just tested it and the blocks that use PUT don't work from ScratchX, but you can still have the extension on the directory but with a warning that not all the blocks will work.
Also if you don't already know, the directory is only for ScratchX extensions.

**Comment by savaka2** [comment]
Assuming this is done, closing, reopen it if it's not done.
