### ISSUE TITLE
HTML5 Canvas

### ISSUE THREAD

**Issue by nathanprocks** [savaka2/scratch-extensions-directory#15]
If you aren't submitting an extension delete this template.  
If you are updating your extension that is hosted using RawGit you don't need the template.

Required stuff:

* JS file URL (preferably on GitHub Pages) (or if you want it hosted on this repo attach the file): 
https://nathanprocks.github.io/Scratch-Canvas/canvas.js
* Author(s) to be listed ([see directory if confused](http://savaka2.github.io/scratch-extensions-directory/)): 
Nathan Piercy
* Description: 
Creates a HTML5 canvas on the stage and adds canvas drawing blocks.

Optional stuff:

* Code on GitHub (url should contain "/blob/") (or Gist): 
* Docs URL: 
* Demo project URL (preferably on GitHub Pages):  
https://nathanprocks.github.io/Scratch-Canvas/Projects/text.sbx  
https://nathanprocks.github.io/Scratch-Canvas/Projects/gradient.sbx

**Comment by savaka2** [comment]
I added a GitHub link https://github.com/nathanprocks/Scratch-Canvas/blob/master/canvas.js
and put the 2 demos in a zip
