### ISSUE TITLE
Scratch2HTML

### ISSUE THREAD

**Issue by champierre** [savaka2/scratch-extensions-directory#16]
Required stuff:

* Extension title: Scratch2HTML
* Author(s) to be listed ([see directory if confused](http://savaka2.github.io/scratch-extensions-directory/)):  Junya Ishihara
* JS file URL (preferably on GitHub Pages) (or if you want it hosted on this repo attach the file): http://champierre.github.io/scratch2html/scratch2html.js
* Description: Scratch2HTML enable to build HTML page using Scratch blocks. 

Optional stuff:

* Code on GitHub (url should contain "/blob/") (or Gist): https://github.com/champierre/scratch2html/blob/gh-pages/scratch2html.js
* Docs URL: https://github.com/champierre/scratch2html
* Demo project URL (preferably on GitHub Pages): http://champierre.github.io/scratch2html/scratch2html_demo.sbx

**Comment by savaka2** [comment]
Used description "Build HTML page using Scratch blocks"
Used docs URL https://github.com/champierre/scratch2html/blob/master/README.md

The demo URL doesn't work, can you fix this or should I make it a download link?

**Comment by champierre** [comment]
Somehow, a direct link to sbx did not work. It works if the sbx file is downloaded to local and opened as extension file.

So, please make

http://champierre.github.io/scratch2html/scratch2html_demo.sbx

a download link.
