### ISSUE TITLE
Base Converter & Transform

### ISSUE THREAD

**Issue by Bax3n** [savaka2/scratch-extensions-directory#27]
# Base Converter
- JS File : https://bax3n.github.io/scratch-extensions/base-converter.js
- Authors : Bax3n
- Description: Converts numbers binary to base-36
- Code on GitHub : https://github.com/Bax3n/scratch-extensions/blob/master/base-converter.js
# Transform
- JS File : https://bax3n.github.io/scratch-extensions/transform.js
- Authors : Bax3n
- Description: Uses the transform property in CSS to move the editor around
- Code on GitHub : https://github.com/Bax3n/scratch-extensions/blob/master/transform.js

**Comment by savaka2** [comment]
In what browser does the transform extension work (and not just make the whole thing not visible)?

**Comment by Bax3n** [comment]
I fixed it (earlier I was testing on scratch.mit.edu, not ScratchX)
