### ISSUE TITLE
Prompt

### ISSUE THREAD

**Issue by Wedrig** [savaka2/scratch-extensions-directory#28]
# Prompt
* JS file URL : wedrig.github.io/scratch-ext/prompt.js
* Author: Wedrig
* Description: Prompts the user
* Code on GitHub : https://github.com/Wedrig/scratch-ext/blob/master/prompt.js
Nothing amazing. Just a first extension.

**Comment by savaka2** [comment]
Used https://wedrig.github.io/scratch-ext/prompt.js
