### ISSUE TITLE
2D Vector Math

### ISSUE THREAD

**Issue by TheMonsterFromTheDeep** [savaka2/scratch-extensions-directory#32]
* JS file URL: https://themonsterfromthedeep.github.io/useful-vectors/v2d.js
* Author(s) to be listed: TheMonsterFromTheDeep
* Description: Basic 2D vector math
* Demo project URL: https://themonsterfromthedeep.github.io/useful-vectors/example.sbx

**Comment by savaka2** [comment]
thanks!

**Comment by savaka2** [comment]
The file https://themonsterfromthedeep.github.io/useful-vectors/example.sbx will not load in ScratchX when used in http://scratchx.org/?url=https://themonsterfromthedeep.github.io/useful-vectors/example.sbx

**Comment by TheMonsterFromTheDeep** [comment]
Which is strange, because when uploading the file directly into the player it works fine. :/

**Comment by savaka2** [comment]
Oh so it does
should I add it without the demo or include it even though the link doesn't work?

**Comment by TheMonsterFromTheDeep** [comment]
Oh I think it might have to do with crossdomain.xml

**Comment by savaka2** [comment]
The extension (js) works fine, not  why the sbx wouldn't

**Comment by TheMonsterFromTheDeep** [comment]
Welp, in any case, do what you think is best; if you have an easy way to add the demo project go ahead, but if it's too much work just skip it.

**Comment by savaka2** [comment]
In one of the extensions I put a link to download the sbx, I might see how I did that and do it again

**Comment by TheMonsterFromTheDeep** [comment]
Sounds good to me. :+1:

**Comment by savaka2** [comment]
there it is
