### ISSUE TITLE
Custom JS Blocks Extension

### ISSUE THREAD

**Issue by kyleplo** [savaka2/scratch-extensions-directory#34]
Required stuff:

* JS file URL: https://kyleplo.github.io/scratch-extensions/customjsblocks.js
* Author(s) to be listed: kyleplo
* Description: Create your own blocks using JavaScript.

Also, I would like to change the JS file url for my Advanced Text to Speech extension to https://kyleplo.github.io/scratch-extensions/advancedtts.js

**Comment by savaka2** [comment]
There is a 404
(maybe you didn't publish the GitHub Pages site?)

**Comment by kyleplo** [comment]
Okay, the URLs should work now.

**Comment by savaka2** [comment]
https://kyleplo.github.io/scratch-extensions/customjsblocks.js redirects to http://kyleplogames.com/scratch-extensions/customjsblocks.js which still gives 404

Also do you want a different documentation URL for Advanced Text to Speech as well? the current URL is http://kyleplogames.com/js/advancedtts.html

**Comment by kyleplo** [comment]
It doesn't return 404 for me. My new docs url is: [https://github.com/kyleplo/scratch-extensions/wiki/Advanced-Text-to-Speech](https://github.com/kyleplo/scratch-extensions/wiki/Advanced-Text-to-Speech)

**Comment by savaka2** [comment]
sorry, my browser cached the redirect, after clearing cache it works
