### ISSUE TITLE
Custom Domain

### ISSUE THREAD

**Issue by KennethSweezy** [savaka2/scratch-extensions-directory#40]
Hello, I would like to purchase a domain for this repositories website. I really love this site and think that it could be enhanced by its very own custom domain that is easier to remember.

I can get a domain with one of the following TLD's:
.site 
.website
.space
.pw
.press
.us 
.host
.club
.live
.online
.store
.site
.life
.fun
.services
.website
.xyz
.icu
.pro
.rocks
.press
.agency

I completely understand if you choose not to accept this offer.
However, if you do accept, I will help with the setup if required.

**Comment by savaka2** [comment]
The current Scratch extension system will be outdated in about 3 months and so will this directory, so I do not wish to do that now
