### ISSUE TITLE
Controller Extension for Scratch Projects

### ISSUE THREAD

**Issue by mytopdog** [savaka2/scratch-extensions-directory#41]
https://gist.github.com/mytopdog/1ef2ccdb67f60994429941090cd016bb

Description

You can now use a controller in Scratch, not really much to say.

https://scratch.mit.edu/projects/255867457/ for a demo.

Flaws:

- Pretty much entirely bodged, but it works.
- Buttons are not defined by a name, just by an id, but documentation is kind of available on the project above.
- Vibration only works on Chrome, but is an easy fix for Firefox.

**Comment by savaka2** [comment]
so would you like me to copy the file to this repo?
