### ISSUE TITLE
Custom Javascript

### ISSUE THREAD

**Issue by hduwu** [savaka2/scratch-extensions-directory#42]
* JS file URL: https://hduwu.github.io/scratch.ex/custom_js.js
* Author(s) to be listed: hduwu
* Description: Runs any kind of Javascript Code

Optional stuff:

* Code on GitHub: https://github.com/hduwu/scratch.ex/blob/master/custom_js.js 
* Demo project URL: https://hduwu.github.io/scratch.ex/customjs_demo.sbx

**Comment by savaka2** [comment]
sorry but I am no longer maintaining the directory

**Comment by hduwu** [comment]
oh, ok. thank you for making the directory anyway.
is there another directory of Scratch extensions? i'd like to submit some of mine somewhere, if not still thank you for making it anyway, since it inspired me to make my own. (haha, this was my first extension tho)

**Comment by savaka2** [comment]
Scratch 3 seems to have no solution for community extensions, so idk
