### ISSUE TITLE
CatX Submission

### ISSUE THREAD

**Issue by LiFaytheGoblin** [savaka2/scratch-extensions-directory#9]
Required stuff:

* Extension title: CatX
* Author(s) to be listed ([see directory if confused](http://savaka2.github.io/scratch-extensions-directory/)): LiFaytheGoblin
* JS file URL (preferably on GitHub Pages) (or if you want it hosted on this repo attach the file): https://github.com/LiFaytheGoblin/ScratchX-Extensions/blob/gh-pages/CatX.js or https://lifaythegoblin.github.io/ScratchX-Extensions/CatX.js
* Description: Create a link to a random cat pic to cutify your projects and surprise your friends <3

Optional stuff:

* Code on GitHub (url should contain "/blob/") (or Gist): https://github.com/LiFaytheGoblin/ScratchX-Extensions/blob/gh-pages/CatX.js
* Demo project URL (preferably on GitHub Pages): https://github.com/LiFaytheGoblin/ScratchX-Extensions/blob/gh-pages/CatX-sample.sbx

**Comment by savaka2** [comment]
Addition is mostly complete  
The 2nd JS file URL is correct (URL you can paste into ScratchX to load extension)

Why does http://scratchx.org/?url=https://lifaythegoblin.github.io/ScratchX-Extensions/CatX-sample.sbx not work?

**Comment by LiFaytheGoblin** [comment]
Oh noo I've had that problem before :\ It usually worked for me after clearing the cache... No idea what the matter is with that :(

**Comment by savaka2** [comment]
I figured something out: it says in the console: `SWF Error: Failed to load SBX: [SecurityErrorEvent type="securityError" bubbles=false cancelable=false eventPhase=2 text="Error #2048"]`

Then it works fine if you don't use https: http://scratchx.org/?url=http://lifaythegoblin.github.io/ScratchX-Extensions/CatX-sample.sbx

**Comment by LiFaytheGoblin** [comment]
Oh, so thaat's the problem?! :O Thanks!

**Comment by savaka2** [comment]
Should I add it just using http://scratchx.org/?url=http://lifaythegoblin.github.io/ScratchX-Extensions/CatX.js and http://scratchx.org/?url=http://lifaythegoblin.github.io/ScratchX-Extensions/CatX-sample.sbx?

Also I've always seen GitHub Pages with just http not https

**Comment by LiFaytheGoblin** [comment]
@savaka2 I use a plugin that tries to use https whenever possible, so my github has https
And yeah, just use that I guess ^.^

**Comment by savaka2** [comment]
Finished! (#10)
